/**
 * Integration işlemlerinin türlerini belirten enum
 * Log kayıtlarının kategorize edilmesi ve filtrelenmesi için kullanılır
 */
export declare enum OperationType {
    SEND_PRODUCTS = "SEND_PRODUCTS",
    FETCH_PRODUCTS = "FETCH_PRODUCTS",
    UPDATE_PRODUCTS = "UPDATE_PRODUCTS",
    DELETE_PRODUCTS = "DELETE_PRODUCTS",
    CHECK_PRODUCT_STATUS = "CHECK_PRODUCT_STATUS",
    GET_BATCH_STATUS = "GET_BATCH_STATUS",
    CREATE_BATCH_REQUEST = "CREATE_BATCH_REQUEST",
    GET_CATEGORIES = "GET_CATEGORIES",
    GET_BRANDS = "GET_BRANDS",
    GET_CATEGORY_ATTRIBUTES = "GET_CATEGORY_ATTRIBUTES",
    CHECK_STOCK = "CHECK_STOCK",
    UPDATE_STOCK = "UPDATE_STOCK",
    SYNC_STOCK = "SYNC_STOCK",
    UPDATE_STOCK_AND_PRICE = "UPDATE_STOCK_AND_PRICE",// Hem stok hem fiyat güncelleme (Trendyol için)
    CREATE_ORDER = "CREATE_ORDER",
    UPDATE_ORDER = "UPDATE_ORDER",
    CANCEL_ORDER = "CANCEL_ORDER",
    FETCH_ORDERS = "FETCH_ORDERS",
    SEND_TRACKING = "SEND_TRACKING",// Kargo takip numarası gönderme (InTransit)
    DELIVER_ORDER = "DELIVER_ORDER",// Teslim durumu bildirme
    CHECK_PACKAGEABLE_ITEMS = "CHECK_PACKAGEABLE_ITEMS",// Birlikte paketlenebilecek ürünleri kontrol et
    CREATE_PACKAGE = "CREATE_PACKAGE",// Paket oluştur
    FETCH_PACKAGES = "FETCH_PACKAGES",// Paketleri listele
    SPLIT_PACKAGE = "SPLIT_PACKAGE",// Paketi böl
    UNPACK_PACKAGE = "UNPACK_PACKAGE",// Paketi aç
    CANCEL_LINE_ITEM = "CANCEL_LINE_ITEM",// Line item iptal et
    UPDATE_PRICES = "UPDATE_PRICES",
    FETCH_PRICES = "FETCH_PRICES",
    SEND_INVOICES = "SEND_INVOICES",
    FETCH_INVOICES = "FETCH_INVOICES",
    CANCEL_INVOICE = "CANCEL_INVOICE",
    HEALTH_CHECK = "HEALTH_CHECK",
    READ = "READ",
    OTHER = "OTHER",
    FETCH_CLAIMS = "FETCH_CLAIMS",
    FETCH_ORDER_STATUS = "FETCH_ORDER_STATUS",
    FETCH_ORDER_CANCELLED = "FETCH_ORDER_CANCELLED",
    FETCH_ORDER_SHIPPED = "FETCH_ORDER_SHIPPED",
    FETCH_ORDER_IN_TRANSIT = "FETCH_ORDER_IN_TRANSIT",
    FETCH_ORDER_DELIVERED = "FETCH_ORDER_DELIVERED",
    FETCH_MISSING_INVOICE_PACKAGES = "FETCH_MISSING_INVOICE_PACKAGES",
    FETCH_UNPACKED_PACKAGES = "FETCH_UNPACKED_PACKAGES",
    FETCH_UNDELIVERED_PACKAGES = "FETCH_UNDELIVERED_PACKAGES",
    ACCEPT_CLAIM = "ACCEPT_CLAIM",
    REJECT_CLAIM = "REJECT_CLAIM"
}
//# sourceMappingURL=operation-type.enum.d.ts.map